// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVyedog__EvwFvI8t4FhX1gQmNz6026ss',
    appId: '1:390419841327:web:c05575a6a1f3af905f21da',
    messagingSenderId: '390419841327',
    projectId: 'agrivision-a902d',
    authDomain: 'agrivision-a902d.firebaseapp.com',
    storageBucket: 'agrivision-a902d.firebasestorage.app',
    measurementId: 'G-B8CELWNZRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNyS0hT5Yq9_4WXldCmsfb76IJ7mNaEk',
    appId: '1:390419841327:android:8ae04a5a0bc2446a5f21da',
    messagingSenderId: '390419841327',
    projectId: 'agrivision-a902d',
    storageBucket: 'agrivision-a902d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrJTChZfmJ8F1R_CjEErYQRHscNSsyAto',
    appId: '1:390419841327:ios:eb831396b81248755f21da',
    messagingSenderId: '390419841327',
    projectId: 'agrivision-a902d',
    storageBucket: 'agrivision-a902d.firebasestorage.app',
    iosClientId: '390419841327-eqh70c6tmvgnc3c1ae9sp7au86phs0gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrivision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrJTChZfmJ8F1R_CjEErYQRHscNSsyAto',
    appId: '1:390419841327:ios:eb831396b81248755f21da',
    messagingSenderId: '390419841327',
    projectId: 'agrivision-a902d',
    storageBucket: 'agrivision-a902d.firebasestorage.app',
    iosClientId: '390419841327-eqh70c6tmvgnc3c1ae9sp7au86phs0gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrivision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVyedog__EvwFvI8t4FhX1gQmNz6026ss',
    appId: '1:390419841327:web:b6d9249593fbedef5f21da',
    messagingSenderId: '390419841327',
    projectId: 'agrivision-a902d',
    authDomain: 'agrivision-a902d.firebaseapp.com',
    storageBucket: 'agrivision-a902d.firebasestorage.app',
    measurementId: 'G-RX972GTT61',
  );
}
